run-name: ${{ github.actor }} está a testar as pipelines com Prettier agora na aula 
on:
  push:
    branches:
      - main

jobs:
  run-defined-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pw-app-s1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies node
        run: npm install

      - name: Run Prettier tests
        run: npm run format

      - name: Build the project and run tests
        run: npm run build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: npx netlify-cli deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}