run-name: ${{ github.actor }} está a testar as pipelines com Prettier
on:
  push:
    branches:
      - main

jobs:
  run-defined-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pw-app-s1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier tests
        run: npm run format
        
      - name: Build the project and run tests
        run: npm run build
